# Generated by Django 3.2 on 2021-07-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tst_app', '0002_auto_20210717_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='seats',
            field=models.IntegerField(null=True),
        ),
    ]
