# Generated by Django 3.2 on 2021-07-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tst_app', '0004_rename_class_trip_classtrain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='date',
            new_name='from_date',
        ),
        migrations.AddField(
            model_name='trip',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
