# Generated by Django 3.2 on 2021-07-18 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tst_app', '0005_auto_20210717_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_no', models.CharField(max_length=100)),
                ('Departure_Time', models.TimeField(blank=True, null=True)),
                ('Arrival_Time', models.TimeField(blank=True, null=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('from_station', models.CharField(blank=True, max_length=100, null=True)),
                ('to_station', models.CharField(blank=True, max_length=100, null=True)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('seats', models.IntegerField(null=True)),
                ('Classtrain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tst_app.train')),
            ],
        ),
    ]
