# Generated by Django 3.2 on 2021-07-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tst_app', '0006_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='seats',
            field=models.IntegerField(default=40, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='seats',
            field=models.IntegerField(),
        ),
    ]
