# Generated by Django 3.2 on 2021-07-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tst_app', '0008_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='Price',
            field=models.IntegerField(default=200),
        ),
    ]
