# Generated by Django 3.2 on 2021-07-20 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tst_app', '0012_auto_20210720_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_trips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
