# Generated by Django 3.2 on 2021-07-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tst_app', '0014_auto_20210720_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='Classtrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tst_app.train'),
        ),
    ]
